import type { UserRole } from "@/types";

/**
 * مطابقة يدوية لخريطة الصلاحيات في apps/api/src/modules/auth/auth.constants.ts
 * ⚠️ لا يوجد Endpoint لجلب الصلاحيات من الخادم - حدّث هذا الملف يدوياً
 * إذا تغيّرت خريطة ROLE_PERMISSIONS بالـ Backend
 */
export const PERMISSIONS = [
  "users:read",
  "users:manage",
  "branches:manage",
  "services:read",
  "services:manage",
  "customers:read",
  "customers:manage",
  "orders:read",
  "orders:create",
  "orders:update-status",
  "orders:cancel",
  "payments:read",
  "payments:create",
  "reports:view",
  "audit:read",
  "settings:manage",
  "invoices:read",
  "invoices:create",
  "invoices:update",
  "invoices:delete",
  "invoices:print",
  "invoices:email",
  "notifications:read",
  "notifications:update",
  "notifications:manage",
  "backup:read",
  "backup:create",
  "backup:restore",
  "backup:manage",
  "inventory:view",
  "inventory:create",
  "inventory:update",
  "inventory:delete",
  "inventory:manage",
  "supplier:view",
  "supplier:manage",
  "purchase:view",
  "purchase:manage",
  "barcode:view",
  "barcode:create",
  "barcode:print",
  "barcode:manage",
  "loyalty:view",
  "loyalty:manage",
  "coupon:view",
  "coupon:manage",
  "membership:view",
  "membership:manage",
  // Phase 9.5 - إغلاق اليوم المحاسبي
  "day:view",
  "day:create",
  "day:close",
  "day:reopen",
  "day:approve",
  // Phase 9.5 - إدارة الموظفين
  "employees:read",
  "employees:manage",
  // Phase 9.5 - مركز الأمان
  "security:view",
  "security:manage",
  // Phase 9.6b - الموارد البشرية
  "attendance:view",
  "attendance:manage",
  "leave:view",
  "leave:manage",
  "leave:approve",
  "payroll:view",
  "payroll:manage",
  "payroll:approve",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Readonly<Record<UserRole, readonly Permission[]>> = {
  ADMIN: PERMISSIONS,
  MANAGER: [
    "users:read",
    "services:read",
    "services:manage",
    "customers:read",
    "customers:manage",
    "orders:read",
    "orders:create",
    "orders:update-status",
    "orders:cancel",
    "payments:read",
    "payments:create",
    "reports:view",
    "invoices:read",
    "invoices:create",
    "invoices:update",
    "invoices:delete",
    "invoices:print",
    "invoices:email",
    "notifications:read",
    "notifications:update",
    "inventory:view",
    "inventory:create",
    "inventory:update",
    "inventory:manage",
    "supplier:view",
    "supplier:manage",
    "purchase:view",
    "purchase:manage",
    "barcode:view",
    "barcode:create",
    "barcode:print",
    "barcode:manage",
    "loyalty:view",
    "loyalty:manage",
    "coupon:view",
    "coupon:manage",
    "membership:view",
    "membership:manage",
    // Phase 9.5
    "day:view",
    "day:create",
    "day:close",
    "day:approve",
    "employees:read",
    "security:view",
    "attendance:view",
    "attendance:manage",
    "leave:view",
    "leave:manage",
    "leave:approve",
    "payroll:view",
  ],
  CASHIER: [
    "services:read",
    "customers:read",
    "customers:manage",
    "orders:read",
    "orders:create",
    "payments:read",
    "payments:create",
    "invoices:read",
    "invoices:create",
    "invoices:print",
    "invoices:email",
    "notifications:read",
    "notifications:update",
    "barcode:view",
    "barcode:print",
    "loyalty:view",
    "coupon:view",
    "membership:view",
  ],
  WORKER: ["orders:read", "orders:update-status", "notifications:read", "notifications:update"],
  DELIVERY: [
    "orders:read",
    "orders:update-status",
    "customers:read",
    "notifications:read",
    "notifications:update",
  ],
};

export function hasPermission(
  role: UserRole | undefined,
  permission: Permission,
): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
}

export function hasAnyRole(
  role: UserRole | undefined,
  ...roles: readonly UserRole[]
): boolean {
  return !!role && roles.includes(role);
}
